#!/usr/bin/env node
// Primary-evidence workflow for the research archive (no AI, no paid APIs).
//
//   npm run evidence:worklist            prioritised list of claims and documents to check (autopsies first)
//   npm run evidence:retrieve -- [--tier 1] [--limit 40] [--dry]
//        fetches documents in worklist order (robots.txt honoured, one request at a time, polite delays,
//        identifying User-Agent from FINANCE_EVIDENCE_USER_AGENT), records every attempt with its real
//        timestamps, and matches each claim's value in the retrieved text. Matches become claim-verification
//        drafts in an import file for the owner to review in Research maintenance — nothing is published here.
//
// Never bypasses access restrictions: paywalls, sign-in pages, 401/402/403, CAPTCHAs and robots.txt
// disallows are recorded as access-restricted and not retried by other routes. Only a hash of each
// retrieved document and short (≤300-character) excerpts are kept.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildWorklist as buildWorklistFor } from "./lib/evidence-priority.mjs";
import { chunkImportItems, mergeImportItems, mergeNeedsHuman, retrieveDocuments } from "./lib/evidence-retrieve.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "research/primary-evidence");
const ARCHIVE = join(ROOT, ".local/build/archive.json");
const args = process.argv.slice(2);
const cmd = args[0];
const opt = (name, dflt) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? (args[i + 1] ?? true) : dflt;
};

if (!existsSync(ARCHIVE)) {
  console.error("Run `npm run build` first (needs .local/build/archive.json).");
  process.exit(1);
}
const archive = JSON.parse(readFileSync(ARCHIVE, "utf8"));
mkdirSync(OUT, { recursive: true });

// ---------------------------------------------------------------- prioritisation (scripts/lib/evidence-priority.mjs)

const buildWorklist = () => buildWorklistFor(archive);

// Claim-verification proposals for Research maintenance → Import (split into files of at most 100 items).
const IMPORT_FILE = /^claim-verifications\.import(?:-\d+)?\.json$/;
const IMPORT_NOTE =
  "Generated by npm run evidence:retrieve (cumulative across runs). Each item proposes a source check for a claim whose recorded value was found in the retrieved document. Import into Research maintenance, compare each excerpt with the document, then publish the drafts you confirm.";
function readImportItems() {
  return readdirSync(OUT)
    .filter((f) => IMPORT_FILE.test(f))
    .sort()
    .flatMap((f) => JSON.parse(readFileSync(join(OUT, f), "utf8")).items ?? []);
}

function worklistMarkdown(w, log) {
  const lastAttempt = new Map();
  for (const e of log?.attempts ?? []) lastAttempt.set(e.documentId, e);
  const lines = [
    "# Primary-evidence worklist",
    "",
    `Generated ${w.generatedAt} from ${w.archiveVersion}. Autopsy deals (tier 1) first, then the remaining deals; within a deal the most consequential fields first. Regenerate with \`npm run evidence:worklist\`.`,
    "",
    "## Counts",
    "",
    "| Measure | Count |",
    "|---|---|",
    ...Object.entries(w.claimsByStatusOverride ?? w.counts.claimsByStatus).map(([k, v]) => `| Claims ${k.replace(/_/g, " ")} (all subjects) | ${v} |`),
    `| Deal claims awaiting a primary-document check | ${w.counts.dealClaimsNeedingPrimaryCheck} |`,
    `| …of which consequential (value, material terms, status, stake, consideration) | ${w.counts.consequentialDealClaims} |`,
    `| …consequential claims supported only by secondary sources | ${w.counts.consequentialOnlySecondary} |`,
    `| Documents to retrieve (primary) | ${w.counts.documentsToRetrieve} (${w.counts.primaryDocumentsToRetrieve}) |`,
    "",
    "## Tier 1: deep autopsies — consequential claims",
    "",
    "| Deal | Field | Recorded value | Status | Source | Last retrieval attempt |",
    "|---|---|---|---|---|---|",
  ];
  const docs = archive.documents;
  for (const c of w.claims.filter((x) => x.tier === 1 && x.rank <= 2)) {
    const d = docs[c.documentId];
    const a = lastAttempt.get(c.documentId);
    lines.push(`| ${c.dealId} | ${c.label} | ${String(c.display).replace(/\|/g, "/").slice(0, 80)} | ${c.status.replace(/_/g, " ")} | ${d.isPrimary ? "primary" : "secondary"}: [${d.publisher}](${d.url}) | ${a ? `${a.outcome} (${a.attemptedAt})` : "not attempted"} |`);
  }
  lines.push("", "## Documents in retrieval order (first 60)", "", "| # | Tier | Document | Primary | Claims | Last attempt |", "|---|---|---|---|---|---|");
  w.documents.slice(0, 60).forEach((d, i) => {
    const a = lastAttempt.get(d.documentId);
    lines.push(`| ${i + 1} | ${d.tier} | [${d.title.replace(/\|/g, "/").slice(0, 70)}](${d.url}) | ${d.isPrimary ? "yes" : "no"} | ${d.claims.length} | ${a ? `${a.outcome} ${a.attemptedAt}` : "—"} |`);
  });
  lines.push("", "Statuses change only when the owner publishes a claim verification (Research maintenance). A search result alone never upgrades a claim.", "");
  return lines.join("\n");
}

// ---------------------------------------------------------------- retrieval (scripts/lib/evidence-retrieve.mjs)

async function retrieve() {
  const ua = process.env.FINANCE_EVIDENCE_USER_AGENT;
  const dry = Boolean(opt("dry", false));
  if (!ua && !dry) {
    console.error("Set FINANCE_EVIDENCE_USER_AGENT to an identifying User-Agent with a contact address (required by SEC fair-access rules), e.g. \"FinanceDesk research contact@example.com\".");
    process.exit(2);
  }
  const tier = Number(opt("tier", 0)) || null;
  const limit = Number(opt("limit", 40));
  const w = buildWorklist();
  const docs = w.documents.filter((d) => !tier || d.tier === tier).slice(0, limit);
  console.log(`${dry ? "Dry run: would retrieve" : "Retrieving"} ${docs.length} documents (${tier ? `tier ${tier}` : "all tiers"})`);
  if (dry) {
    for (const d of docs) console.log(`  ${d.url}  (${d.claims.length} claims)`);
    return;
  }
  const logPath = join(OUT, "retrieval-log.json");
  const log = existsSync(logPath) ? JSON.parse(readFileSync(logPath, "utf8")) : { format: "finance-evidence-retrieval-log-v1", attempts: [] };
  const run = await retrieveDocuments({ docs, claims: archive.claims, ua, onAttempt: (e) => console.log(`  ${e.outcome.padEnd(22)} ${e.url}`) });
  // The attempt log is append-only: earlier attempts keep their original timestamps.
  log.attempts.push(...run.attempts);
  writeFileSync(logPath, `${JSON.stringify(log, null, 1)}\n`);
  // Proposals accumulate across runs (nothing unimported is lost by re-running) and are split into
  // import files of at most 100 items, the limit of Research maintenance → Import.
  const importItems = mergeImportItems(readImportItems(), run.candidates);
  for (const f of readdirSync(OUT).filter((x) => IMPORT_FILE.test(x))) rmSync(join(OUT, f));
  const files = chunkImportItems(importItems);
  for (const f of files) writeFileSync(join(OUT, f.name), `${JSON.stringify({ format: "finance-research-import-v1", note: IMPORT_NOTE, items: f.items }, null, 1)}\n`);
  const humanPath = join(OUT, "needs-human-check.json");
  const prevHuman = existsSync(humanPath) ? JSON.parse(readFileSync(humanPath, "utf8")).items ?? [] : [];
  writeFileSync(humanPath, `${JSON.stringify({ updatedAt: new Date().toISOString(), items: mergeNeedsHuman(prevHuman, run.needsHuman) }, null, 1)}\n`);
  const outcomes = {};
  for (const a of run.attempts) outcomes[a.outcome] = (outcomes[a.outcome] ?? 0) + 1;
  console.log(`Outcomes this run: ${JSON.stringify(outcomes)}. Candidate source checks: ${run.candidates.length} this run, ${importItems.length} in total (${files.map((f) => f.name).join(", ")}). Needs human check: ${run.needsHuman.length} this run.`);
  writeFileSync(join(OUT, "WORKLIST.md"), worklistMarkdown(w, log));
}

if (cmd === "worklist") {
  const w = buildWorklist();
  const logPath = join(OUT, "retrieval-log.json");
  const log = existsSync(logPath) ? JSON.parse(readFileSync(logPath, "utf8")) : null;
  writeFileSync(join(OUT, "worklist.json"), `${JSON.stringify(w, null, 1)}\n`);
  writeFileSync(join(OUT, "WORKLIST.md"), worklistMarkdown(w, log));
  console.log(`worklist: ${w.counts.dealClaimsNeedingPrimaryCheck} deal claims (${w.counts.consequentialDealClaims} consequential, ${w.counts.tier1Claims} in autopsies) across ${w.documents.length} documents → research/primary-evidence/`);
} else if (cmd === "retrieve") {
  await retrieve();
} else {
  console.error("Usage: node scripts/evidence.mjs worklist | retrieve [--tier 1] [--limit 40] [--dry]");
  process.exit(1);
}
